coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
ignore:
  - "docs/"
  - "src/backup/"
  - "src/IO_legacy.jl"
  - "src/IO.jl"
  - "src/legacy_code.jl"
  - "notebooks/"
