# input TOML for ladderDGA
[Model]
U    = 1.0
mu   = 0.5
beta = 25.0 #25.0
nden = 1.0
Dimensions = 3

[Simulation]
Nk        = 4            # IMPORTANT: in Fortran this is Nk x Nk and generated bei make_klist. TODO: adaptiv mesh
tail_correction = "nothing" #"Richardson" # Nothing, Richardson, Shanks
lambda_correction = "sp"     # nothing, sp, sp_ch
force_full_local_bosonic_sum = false   # instead of a usable interval for local quantities, use all bosonic frequencies
force_full_bosonic_sum = false        # instead of a usable interval for non local quantities (EoM), use all bosonic frequencies
force_max_usable = false         # instead of comon usable range, use individual maximum ranges (fortran: true)
force_full_bosonic_chi = false        # compute all omega frequencies for chi and trilex
chi_unusable_fill_value = "chi_lambda" # can be "0", "chi_lambda" or "chi". sets either 0, lambda corrected or non lambda corrected values outside usable omega range
chi_only = false          # Should only chis_omega and chich_omega be calculated?
rhs  = ""                 # TODO: implement possible modes: native (fixed for tc, error_comp for naive), 
                          #                                 fixed (n/2 (1 - n/2) - sum(chi_ch)), 
                          #                                 error_comp (chi_loc_ch + chi_loc_sp - chi_ch)
fermionic_tail_coeffs = [0,1]
bosonic_tail_coeffs = [0,1]


[Environment]
inputDataType = "jld2"      # jld2, text, parquet, TODO: implement hdf5
writeFortran = false
loadAsymptotics = false
#inputDir = "/home/julian/Hamburg/ladderDGA3D_FFT_small"
inputDir = "/home/julian/Hamburg/lDGA_shift_tests/data/20_red_shift"
freqFile = "freqList.jld2"
inputVars = "ED_out.jld2"
asymptVars = "vars_asympt_sums.jld"
cast_to_real = false             # TODO: not implemented. cast all arrays with vanishing imaginary part to real
loglevel = "debug"        # error, warn, info, debug
logfile = "stderr" #"run.out"        # STDOUT, STDERR, filename

[Debug]
read_bubble = false
