[Model]
kGrid = "3Dsc-0.2041241452319315"

[Simulation]
Nk        = [4]                         # number of k points in each dimension
chi_asympt_method = "direct"            # direct/sc/nothong, see BSE_SC module for more
chi_asympt_shell = 4                   # Integer >0 improves nu,nu' asymptotics of the generalized susceptibilityself consistently. Physical susceptibilities must be given in the input file. 0 deactivates this.

# WARNING: DO NOT TOUCH ANY SIMULATION PARAMETERS BELOW UNLESS YOU KNOW WHAT YOU ARE DOING!!!!
usable_prct_reduction = 0.0             # safety cutoff for usable ranges, 0.0 means all values where chi is positive and strictly decreasing
omega_smoothing = "nothing"             # nothing, range, full. Smoothes data after nu, nu' sums. Set range to only use smoothing in order to find the usable range (default)


[Environment]
inputDir = ""                           # path to input dir
inputVars = ""                          # name of input file
logfile = "stderr"                      # STDOUT, STDERR, filename

# WARNING: DO NOT TOUCH ANY ENVIRONMENT PARAMETERS BELOW UNLESS YOU KNOW WHAT YOU ARE DOING!!!!
loglevel = "debug"                      # error, warn, info, debug

[Debug]
full_EoM_omega = true                  # compatibility flag for fortran code
