name: Documentation

on: 
  push:
    branches:
      - master
      - dev
      - dev_cleanup
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia -e 'using Pkg; Pkg.Registry.update(); Pkg.instantiate(); cd("docs"); Pkg.activate(); Pkg.instantiate(); include("make.jl");'
